- name: configure mysql sever 
  hosts: mysql 
  become: yes 
  tasks: 
  - name: Install mysql server 
    ansible.builtin.package:
      name: mysql-server
      state: installed 

  - name: start and enabled the mysql server 
    ansible.builtin.service: 
      name: mysqld
      state: started 
      enabled: yes 